# Exercise on Joins and anti-joins: add information from other tables

In [1]:
# import libraries - solution
import pandas as pd
import numpy as np

# Set some Pandas options: maximum number of rows/columns it's going to display
#pd.set_option('display.max_rows', 1000)
#pd.set_option('display.max_columns', 100)

## Load data from clinical trial

Data comes in two different files. The file `predimed_records.csv` file contains the clinical data for each patient, except which diet group they were assigned. The file `predimed_mapping.csv` contain the information of which patient was assigned to which diet group.

In [28]:
# solution
df = pd.read_csv('../../data/predimed_records.csv')
df.head()

,patient-id,location-id,sex,age,smoke,bmi,waist,wth,htn,diab,hyperchol,famhist,hormo,p14,toevent,event
0,436,4,Male,58,Former,33.53,122,0.753086,No,No,Yes,No,No,10,5.374401,Yes
1,1130,4,Male,77,Current,31.05,119,0.730061,Yes,Yes,No,No,No,10,6.097194,No
2,1131,4,Female,72,Former,30.86,106,0.654321,No,Yes,No,Yes,No,8,5.946612,No
3,1132,4,Male,71,Former,27.68,118,0.694118,Yes,No,Yes,No,No,8,2.907598,Yes
4,1111,2,Female,79,Never,35.94,129,0.806250,Yes,No,Yes,No,No,9,4.761123,No

In [3]:
# solution
df_info = pd.read_csv('../../data/predimed_mapping.csv')
df_info.head()

   location-id  patient-id           group
0            2         885   MedDiet + VOO
1            1         182  MedDiet + Nuts
2            1         971  MedDiet + Nuts
3            2         691  MedDiet + Nuts
4            2         632         Control

There were 5 different locations where the study was conducted, each one gave an identification number `patient-id` to each participant.

In [4]:
# solution
df_info['location-id'].unique()

array([2, 1, 3, 4, 5])

## 1. Add diet information to the patients' records

* For how many patients do we have clinical information? (i.e., rows in `df`)
* For how many patients do we have diet information? (i.e., rows in `info`)

In [5]:
# solution
len(df)

6324

In [6]:
# solution
len(df_info)

6287

### **Exercise** : 

Combine the two tables into one, where all patient informaiton is available.

In [7]:
# solution

# Explore the date
len(df['patient-id'].unique())

1324

If there are only 1324 unique patient-ids, we can't merge only based on the patient-id because there are multiple rows for the same patient. We need to use the location-id as well.

In [8]:
# solution

len(df['location-id'].unique())

5

In [9]:
# solution

1324*5

6620

Looks like not all patients have been tested at all locations.

#### Solution - naive O(n*m)

In [10]:
# solution
# final check - check if the indices are consequitive

In [29]:
# solution

# add a column group
df.insert(0, 'group_2_for_loops', '')

In [30]:
# %%timeit
# solution

# 2 for loops

groups = []

for patient in df['patient-id'].unique():
    df_patient = df[df['patient-id'] == patient]
    for loc in df_patient['location-id']:
        row_df_info = df_info[(df_info['patient-id'] == patient) &
                            (df_info['location-id'] == loc)]
        if len(row_df_info) == 0:
            group = np.nan
        if len(row_df_info) == 1:
            group = row_df_info.group.values[0]
        indx_df = df[(df['patient-id'] == patient) &
                            (df['location-id'] == loc)].index.tolist()
        df.loc[indx_df, 'group_2_for_loops'] = group

#### Solution - a bit better

In [31]:
# %%timeit
# solution

# For loop over patient-id

groups = []
count = 0
for i, patient in enumerate(df['patient-id']):
    loc = df['location-id'][i]
    row_df_info = df_info[(df_info['patient-id'] == patient) &
                            (df_info['location-id'] == loc)]
    if len(row_df_info) == 0:
        group = np.nan
        count+=1
    if len(row_df_info) == 1:
        group = row_df_info.group.values[0]
    if len(row_df_info) > 1:
        print(f'error repeated rows for patient {patient} at {loc}')

    groups.append(group)

In [23]:
# solution

# check if the numebr of nans is correct
len(df_info) + count

6324

In [25]:
# solution

# check if the groups list is as long as the dataframe

print(len(groups))
print(len(df))

6324
6324

In [32]:
# solution 

# insert the group column
df.insert(len(df.columns), 'group', groups)

In [37]:
df[df['group'] != df['group_2_for_loops']]

,group_2_for_loops,patient-id,location-id,sex,age,smoke,bmi,waist,wth,htn,diab,hyperchol,famhist,hormo,p14,toevent,event,group
69,NaN,402,3,Male,72,Former,31.24,103,0.651899,Yes,No,Yes,No,NaN,7,3.616701,No,NaN
274,NaN,292,3,Male,70,Former,21.35,80,0.516129,No,Yes,No,No,No,9,3.759069,Yes,NaN
406,NaN,583,3,Male,67,Current,30.48,97,0.602484,Yes,No,Yes,No,No,10,6.559890,No,NaN
511,NaN,883,1,Female,55,Never,34.24,103,0.715278,Yes,Yes,Yes,No,No,10,6.132786,No,NaN
559,NaN,915,2,Female,64,Never,33.06,114,0.690909,Yes,No,Yes,No,No,11,5.708419,No,NaN
609,NaN,830,2,Male,62,Current,25.78,107,0.668750,Yes,No,Yes,No,No,11,3.928816,No,NaN
766,NaN,675,4,Female,67,Never,29.79,93,0.636986,Yes,No,Yes,Yes,No,12,5.347023,No,NaN
796,NaN,382,5,Female,73,Never,28.69,98,0.680556,No,No,Yes,No,No,8,4.394250,No,NaN
887,NaN,312,5,Female,67,Never,30.77,96,0.653061,Yes,No,Yes,No,No,10,1.787817,No,NaN
1025,NaN,989,3,Female,72,Never,34.48,101,0.687075,Yes,No,Yes,No,No,11,4.887064,No,NaN
1410,NaN,880,3,Male,60,Never,29.51,106,0.616279,Yes,Yes,Yes,No,No,7,4.966461,No,NaN
1419,NaN,937,3,Male,63,Current,25.62,100,0.555556,Yes,No,No,No,NaN,9,6.784394,No,NaN
1615,NaN,825,4,Male,68,Former,31.23,107,0.652439,Yes,Yes,Yes,No,NaN,10,2.127310,No,NaN
1634,NaN,819,4,Female,69,Never,30.44,104,0.658228,Yes,No,Yes,No,No,11,2.694045,No,NaN
2806,NaN,36,1,Male,55,Never,28.91,98,0.593939,Yes,Yes,Yes,No,No,8,2.874743,No,NaN
3072,NaN,974,4,Male,77,Former,27.35,102,0.658065,Yes,Yes,Yes,No,No,9,6.841889,No,NaN
3339,NaN,520,5,Female,66,Never,27.34,97,0.633987,Yes,No,Yes,Yes,No,6,5.897331,No,NaN
3841,NaN,286,3,Male,67,Current,28.33,101,0.604790,No,No,Yes,Yes,No,8,5.585216,No,NaN
3898,NaN,707,5,Female,63,Never,36.31,110,0.718954,No,Yes,Yes,No,No,7,5.623546,No,NaN
4137,NaN,1141,4,Female,61,Never,23.94,86,0.547771,No,No,Yes,No,No,9,5.785079,No,NaN
4343,NaN,932,1,Male,63,Former,30.37,100,0.613497,Yes,Yes,Yes,No,No,9,6.609172,No,NaN
4560,NaN,1197,1,Male,68,Current,31.83,105,0.621302,Yes,No,No,No,No,10,6.138261,No,NaN
5034,NaN,1220,5,Female,70,Never,30.09,98,0.608696,Yes,No,No,Yes,No,10,4.982888,No,NaN
5228,NaN,1189,3,Female,59,Never,35.82,112,0.746667,Yes,Yes,Yes,No,No,5,1.900068,No,NaN
5255,NaN,31,4,Female,68,Never,27.12,92,0.617450,No,Yes,Yes,No,No,7,6.069815,No,NaN
5279,NaN,879,5,Male,77,Former,28.49,109,0.656627,Yes,Yes,No,No,No,9,2.877481,No,NaN
5485,NaN,985,5,Female,67,Never,38.21,119,0.762821,Yes,No,Yes,No,No,8,2.239562,No,NaN
5502,NaN,344,4,Female,68,Never,34.68,96,0.690647,No,Yes,No,No,No,3,1.941136,No,NaN
5583,NaN,939,3,Male,65,Current,30.30,95,0.533708,Yes,Yes,Yes,Yes,No,12,2.182067,Yes,NaN
5802,NaN,217,5,Female,65,Never,35.88,105,0.709459,Yes,No,Yes,No,No,8,2.789870,No,NaN
5862,NaN,354,1,Female,59,Never,34.55,102,0.658065,Yes,No,Yes,No,No,8,5.787817,No,NaN
5875,NaN,68,3,Female,68,Never,28.41,101,0.660131,Yes,Yes,Yes,Yes,No,11,3.520876,No,NaN
5903,NaN,150,3,Male,79,Never,25.39,91,0.587097,No,Yes,No,No,No,6,3.701574,Yes,NaN
5930,NaN,253,4,Male,64,Never,33.87,112,0.687117,Yes,Yes,No,No,No,8,2.762491,No,NaN
5936,NaN,148,4,Female,70,Never,24.02,85,0.505952,Yes,Yes,Yes,No,No,10,2.800821,No,NaN
6004,NaN,49,3,Male,66,Never,26.15,98,0.593939,Yes,Yes,Yes,No,NaN,10,3.206023,No,NaN
6089,NaN,332,5,Male,66,Never,28.19,107,0.633136,Yes,No,Yes,No,NaN,9,3.561944,No,NaN

#### Solution - O(n+m)

In [41]:
# %%timeit
# solution - optimal
df_with_info = df.merge(df_info, on = ['patient-id', 'location-id'], how = 'left')

In [43]:
# solution
len(df_with_info)

6324

# 4. Save final result in `processed_data_predimed.csv`

1. Using the `.to_csv` method of Pandas DataFrames

In [19]:
df_without_dropped.to_csv('processed_data_predimed.csv', index=None)